# Auto-generated by req-flow
# REQ-001: The robot shall trigger a low battery warning when charge drops below 20%.

import pytest
from src.battery import Battery


@pytest.fixture
def battery_full():
    return Battery(charge=100.0)

@pytest.fixture
def battery_20():
    return Battery(charge=20.0)

@pytest.fixture
def battery_19():
    return Battery(charge=19.0)

@pytest.fixture
def battery_15():
    return Battery(charge=15.0)

@pytest.fixture
def battery_21():
    return Battery(charge=21.0)

@pytest.fixture
def battery_0():
    return Battery(charge=0.0)

@pytest.fixture
def battery_95():
    return Battery(charge=95.0)

def test_drain_sets_warning_active_when_charge_below_20(battery_20):
    battery = battery_20
    battery.drain(1)
    assert battery.charge == 19.0
    assert battery.warning_active is True

def test_drain_does_not_set_warning_active_when_charge_above_20(battery_21):
    battery = battery_21
    battery.drain(3)
    assert battery.charge == 20.0
    assert battery.warning_active is False

def test_recharge_sets_warning_active_to_false_when_charge_reaches_20(battery_15):
    battery = battery_15
    battery.recharge(5)
    assert battery.charge == 20.0
    assert battery.warning_active is False

def test_recharge_sets_warning_active_to_false_when_charge_exceeds_20(battery_19):
    battery = battery_19
    battery.recharge(2)
    assert battery.charge == 21.0
    assert battery.warning_active is False

def test_recharge_does_not_change_warning_active_if_charge_above_20(battery_21):
    battery = battery_21
    battery.recharge(10)
    assert battery.charge == 31.0
    assert battery.warning_active is False

def test_recharge_does_not_exceed_100_percent(battery_95):
    battery = battery_95
    battery.recharge(10)
    assert battery.charge == 100.0
